import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Nav from '@/components/Nav'
import Explore from '@/components/Explore'
import Setup from '@/components/Setup'
import HotCollections from '@/components/HotCollections'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <main className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
   {/** NAV BAR */}
     <div className='z-100'>
     <Nav />

     </div>
    
    {/** CONTENT */}
    <div className='z-1'>
    <Explore />
      <Setup />
      <HotCollections />


    </div>
     

    </main>
  )
}
