import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Nav from '@/components/Nav'
import Explore from '@/components/Explore'
import Setup from '@/components/Setup'
import HotCollections from '@/components/HotCollections'
import NewItems from '@/components/NewItems'
import TopSellers from '@/components/TopSellers'
import BrowseCategory from '@/components/BrowseCategory'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <main className=''>
      <Head>
        <title>UltraVerse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
   {/** NAV BAR */}
   
     <Nav />

    
    {/** CONTENT */}
  
    <Explore />
      <Setup />
      <HotCollections />
      <NewItems />
      <TopSellers />
      <BrowseCategory/>



     

    </main>
  )
}
